name: Build and Deploy

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: luxuryphile
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

    #   - name: Build and Push Web Docker image
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: ./Web
    #       file: ./Web/Dockerfile
    #       push: true
    #       tags: your-registry/web:${{ github.sha }}

    #   - name: Run Bicep infrastructure deployment
    #     run: |
    #       az deployment sub create --location <azure-location> --template-file <path-to-your-bicep-file> --parameters <path-to-your-parameters-file>

    #   - name: Deploy container to Azure
    #     run: |
    #       az container create --resource-group <your-resource-group> --name <your-container-name> --image your-acr-name.azurecr.io/your-container-name:${{ github.sha }} --registry-username <acr-username> --registry-password <acr-password>
