name: Build and Deploy

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build-image:
    name: Build docker container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: luxuryphile.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sample
          file: ./sample/Dockerfile
          push: true
          tags: luxuryphile.azurecr.io/luxuryphile/web:${{ github.sha }}

    # TODO: scan container for vulnarabilities

  deploy_dev:
    name: DEV Deploy
    runs-on: ubuntu-latest
    needs: build-image

    env:
      custom_env_variable: "DEV value"
      url: https://luxuryphile-dev.azurewebsites.net

    environment:
      name: Dev
      url: ${{ env.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Bicep infrastructure deployment
        run: |
          az deployment sub create \
            --location 'westeurope' \
            --template-file ./main.bicep  \
            --name 'deploy-luxuryfile-bicep'
            --parameters location=westeurope \
            --parameters rgName=rg-luxuryphile-dev \
            --parameters webAppName=as-luxuryphile-web-dev \
            --parameters dockerRegistryHost=${{ secrets.DOCKER_LOGIN_SERVER }} \
            --parameters dockerRegistryServerUsername=${{ secrets.DOCKER_USERNAME }} \
            --parameters dockerRegistryServerPassword=${{ secrets.DOCKER_PASSWORD }} \
            --parameters dockerImage=luxuryphile/web:${{ github.sha }} \

#   - name: Deploy container to Azure
#     run: |
#       az container create --resource-group <your-resource-group> --name <your-container-name> --image your-acr-name.azurecr.io/your-container-name:${{ github.sha }} --registry-username <acr-username> --registry-password <acr-password>

# Log all env variables
#   - name: Log Environment Variables
#     run: |
#       env
